AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Nextwork DevOps CI/CD Pipeline'

Parameters:
  GitHubOwner:
    Type: String
    Default: "Heeyaichen"
    Description: GitHub repository owner

  GitHubRepo:
    Type: String
    Default: "aws-web-app-devOps"
    Description: GitHub repository name

  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub repository branch
     
  GitHubConnectionArn:
    Type: String
    Description: GitHub connection ARN from CodeStar Connections

  ApplicationName:
    Type: String
    Default: "nextwork-devops-cicd"
    Description: CodeDeploy application name

  DeploymentGroupName:
    Type: String
    Default: "nextwork-devops-cicd-deployment-group"
    Description: CodeDeploy deployment group name

  ArtifactBucketName:
    Type: String
    Default: "nextwork-devops-cicd-chen"
    Description: Name of the existing S3 bucket for artifacts
  
  BuildInfraStackName:
    Type: String
    Default: "build-infra-stack"
    Description: Name of the infrastructure stack that exports resources

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: nextwork-devops-cicd
      RoleArn: 
        Fn::ImportValue: !Sub "${BuildInfraStackName}-CodePipelineServiceRole"
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub ${GitHubOwner}/${GitHubRepo}
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
              Namespace: SourceVariables

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Fn::ImportValue: !Sub "${BuildInfraStackName}-CodeBuildProjectName"
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: '1'
              Configuration:
                ApplicationName: !Ref ApplicationName
                DeploymentGroupName: !Ref DeploymentGroupName
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1

Outputs:
  PipelineURL:
    Description: URL to the CodePipeline console
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
